export const DATABASE_PORT = 'DATABASE_PORT';
export const DATABSE_HOST = 'DATABSE_HOST';
export const DATABASE_NAME = 'DATABASE_NAME';
export const DATABASE_USER = 'DATABASE_USER';
export const DATABASE_PASSWORD = 'DATABASE_PASSWORD';